Change: order of testing workflow
* With the previous version, the tests would not run if the project
was not the 'FileMicroservice'.
* Changed the workflow so that the tests will run, regardless of the
project name.

diff --git a/.github/workflows/template-build-test.yml b/.github/workflows/template-build-test.yml
--- a/.github/workflows/template-build-test.yml
+++ b/.github/workflows/template-build-test.yml
@@ -41,6 +41,7 @@ jobs:
         run: bash ${{ inputs.test-location }}/create-mock-appsettings.sh
       
       - name: "Run test on project"
+        if: success() || failure() # run this step even if previous step failed
         run: dotnet test ${{ inputs.test-location }} --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
 
       - name: "Create Test Report"
